### PR TITLE
Add logo svgs

### PR DESCRIPTION
**Pull request by mikeyrayvon**

### CODE REVIEW

**Comment by varffs** [comment]
You have to set svg width & height values explicit as Safari freaks out otherwise

screen shot 2016-08-24 at 17 22 37

**Comment by mikeyrayvon** [comment]
maybe flex 💭 hm

**Comment by varffs** [comment]
maybe. as far as i know its just a safari bug but not fixed for ages

**Comment by mikeyrayvon** [comment]
i think it works if i add `preserveAspectRatio="none"` to the svg but lets see

**Comment by mikeyrayvon** [comment]
oh wait no that doesnt make sense. damn explicit thats so f annoying

**Comment by mikeyrayvon** [comment]
oh no it scales with width only. css was just bad

**Pull request merged**
