### PR TITLE
Feature vertical layout

### PR DESCRIPTION
**Pull request by varffs**
- set main content holder to 100vh minus header and footer heights
- use variables for hard header and footer heights to be adjusted when needed
- fix no bottom margin col declaration

Currently this vertically centers anything that is smaller than the overflow. we can decide if we want this to be the case after testing

### CODE REVIEW

**Comment by mikeyrayvon** [comment]
this calc isnt working for me
screen shot 2016-08-24 at 6 08 00 pm

**Comment by varffs** [comment]
thats what it should look like. it not laying out correctly?

**Comment by mikeyrayvon** [comment]
no i dont think so
screen shot 2016-08-24 at 6 18 08 pm

**Comment by mikeyrayvon** [comment]
shouldnt it be `max-height` anyways?

**Comment by varffs** [comment]
No it is min-height so when the content is better it doesnt constrain

**Comment by varffs** [comment]
So it is working correctly. The screenshot of the single editorial is as it should be as that template isn't styled yet so doesnt have proper heights set on the content. This approach requires heights set for content that vertically centers and changes. This is fine as it is related to image heights. So the archive for editorial works as that styling has a height value set that relates to the largest possible image. Pages which don't change heights with hover or whatever will work without explicit heights set as auto should do the job

**Comment by mikeyrayvon** [comment]
so which template is styled? so i can test it

**Comment by mikeyrayvon** [comment]
doesnt work on my screen with the image size we have set. and clay wants the images to be bigger on larger screens, were going to have to set our image sizes for bigger containers anyways.  we need to set breakpoints for the images in order for this to work. but max-height makes the images squish so idk what to do
screen shot 2016-08-26 at 10 02 54 am

**Comment by mikeyrayvon** [comment]
the only way i can think of making this work is setting `max-height` px on the images in js

**Comment by varffs** [comment]
we just need to do height based media queries for these layouts, or assume a constant ratio and do it in the larger responsive sizes.

yes for the moment to fix 13" screens we do need to make that image size shorter for that layout

we shouldn't be serving oversize images to smaller screens so we need a solution to display the correct image on different screen sizes. I had previously thought `display: none` stopped the request for an image but I am wrong so I need to work that out for something else. We should use the same solution here. At the moment we should just build to fix 13" screen and then do a feature branch later to upscale these layouts.

this is good to go unless you want me (or you) to fix this specific layout for 13" screens before merge?

**Pull request merged**
